# Generated by Django 5.2.17 on 2026-09-24 09:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100, unique=True)),
                ('api_url', models.URLField(blank=True, max_length=500)),
                ('data_topic', models.CharField(max_length=200)),
                ('control_topic', models.CharField(max_length=200)),
                ('wait_time', models.IntegerField(default=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
